// Copyright (c) 2022 Anders Xiao. All rights reserved.
// https://github.com/endink

#pragma once
#include "Stats/Stats.h"


DECLARE_STATS_GROUP(TEXT("MediaPipe4U Stats"),STATGROUP_M4U, STATCAT_MediaPipe4U); 
DECLARE_CYCLE_STAT_EXTERN(TEXT("Pose Solve"), STAT_PoseSolve, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Hand Solve"), STAT_HandSolve, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Head Solve"), STAT_HeadSolve, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Location Solve"), STAT_LocationSolve, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Ground IK Solve"), STAT_GroundIKSolve, STATGROUP_M4U, MEDIAPIPE_API);

DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Image Source FPS"), STAT_ImageSourceFPS, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Image Streaming FPS"), STAT_ImageStreamingFPS, STATGROUP_M4U, MEDIAPIPE_API);

DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Image Frame Width"), STAT_FrameWidth, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Image Frame Height"), STAT_FrameHeight, STATGROUP_M4U, MEDIAPIPE_API);

DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Frame Pool Idle"), STAT_FramePoolIdle, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Frame Pool Busy"), STAT_FramePoolBusy, STATGROUP_M4U, MEDIAPIPE_API);

DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Movement Velocity X"), STAT_MovementVelocityX, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Movement Velocity Y"), STAT_MovementVelocityY, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Movement Velocity Z"), STAT_MovementVelocityZ, STATGROUP_M4U, MEDIAPIPE_API);

DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Animation FPS"), STAT_AnimFPS, STATGROUP_M4U, MEDIAPIPE_API);
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Pose Solver FPS"), STAT_PoseSolverFPS, STATGROUP_M4U, MEDIAPIPE_API);